// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pd2/AdminPanel.tsx": () => import("../components/mockups/pd2/AdminPanel.tsx"),
  "./components/mockups/pd2/Dashboard.tsx": () => import("../components/mockups/pd2/Dashboard.tsx"),
  "./components/mockups/pd2/Landing.tsx": () => import("../components/mockups/pd2/Landing.tsx"),
  "./components/mockups/pd2/ScanResult.tsx": () => import("../components/mockups/pd2/ScanResult.tsx"),
  "./components/mockups/pediderm/History.tsx": () => import("../components/mockups/pediderm/History.tsx"),
  "./components/mockups/pediderm/Results.tsx": () => import("../components/mockups/pediderm/Results.tsx"),
  "./components/mockups/pediderm/Upload.tsx": () => import("../components/mockups/pediderm/Upload.tsx")
};
